export const data = JSON.parse("{\"key\":\"v-607ce1a9\",\"path\":\"/posts/DevOps/Nacos%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E4%BD%BF%E7%94%A8.html\",\"title\":\"Nacos配置中心使用\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Nacos配置中心使用\",\"author\":\"郑天祺\",\"tag\":[\"SpringCloud\",\"nacos-config\"],\"category\":[\"spring\"],\"date\":\"2019-11-25T16:38:00.000Z\",\"description\":\"一、启动Nacos Server 1、启动方式可见 Nacos 官网 2、在配置列表里配置自己的配置，按照规范填写各项。 user.name=zhengtianqi user.password=123456\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://zhengtianqi.gitee.io/posts/DevOps/Nacos%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E4%BD%BF%E7%94%A8.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"郑天祺的博客\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Nacos配置中心使用\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"一、启动Nacos Server 1、启动方式可见 Nacos 官网 2、在配置列表里配置自己的配置，按照规范填写各项。 user.name=zhengtianqi user.password=123456\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"郑天祺\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"SpringCloud\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"nacos-config\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2019-11-25T16:38:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Nacos配置中心使用\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2019-11-25T16:38:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"郑天祺\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":2.62,\"words\":785},\"filePathRelative\":\"posts/DevOps/Nacos配置中心使用.md\",\"localizedDate\":\"2019年11月26日\",\"excerpt\":\"<h1> 一、启动Nacos Server</h1>\\n<p>1、启动方式可见 <a href=\\\"https://nacos.io/zh-cn/docs/quick-start.html\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">Nacos 官网</a></p>\\n<p>2、在配置列表里配置自己的配置，按照规范填写各项。</p>\\n<div class=\\\"language-java line-numbers-mode\\\" data-ext=\\\"java\\\"><pre class=\\\"language-java\\\"><code>user<span class=\\\"token punctuation\\\">.</span>name<span class=\\\"token operator\\\">=</span>zhengtianqi\\nuser<span class=\\\"token punctuation\\\">.</span>password<span class=\\\"token operator\\\">=</span><span class=\\\"token number\\\">123456</span>\\n</code></pre><div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\"><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div></div></div>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
