export const data = JSON.parse("{\"key\":\"v-343cfb76\",\"path\":\"/posts/java/Kafka%E7%9A%84%E7%AE%80%E5%8D%95%E4%BD%BF%E7%94%A8.html\",\"title\":\"Kafka的简单使用\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Kafka的简单使用\",\"author\":\"郑天祺\",\"tag\":[\"SpringCloud\"],\"category\":[\"spring\"],\"date\":\"2020-12-14T12:59:00.000Z\",\"description\":\"1、安装kafka http://kafka.apache.org/quickstart （linux版） windows版： 首先cmd到kafka的bin下 其中启动内置的zk用：zookeeper-server-start.bat D:\\\\environment\\\\kafka_2.12-2.3.0\\\\config\\\\zookeeper.properties 启动Kafka用：kafka-server-start.bat D:\\\\environment\\\\kafka_2.12-2.3.0\\\\config\\\\server.properties\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://zhengtianqi.gitee.io/posts/java/Kafka%E7%9A%84%E7%AE%80%E5%8D%95%E4%BD%BF%E7%94%A8.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"郑天祺的博客\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Kafka的简单使用\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"1、安装kafka http://kafka.apache.org/quickstart （linux版） windows版： 首先cmd到kafka的bin下 其中启动内置的zk用：zookeeper-server-start.bat D:\\\\environment\\\\kafka_2.12-2.3.0\\\\config\\\\zookeeper.properties 启动Kafka用：kafka-server-start.bat D:\\\\environment\\\\kafka_2.12-2.3.0\\\\config\\\\server.properties\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"郑天祺\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"SpringCloud\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2020-12-14T12:59:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Kafka的简单使用\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2020-12-14T12:59:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"郑天祺\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":2.13,\"words\":638},\"filePathRelative\":\"posts/java/Kafka的简单使用.md\",\"localizedDate\":\"2020年12月14日\",\"excerpt\":\"<h1> 1、安装kafka</h1>\\n<p><a href=\\\"http://kafka.apache.org/quickstart\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">http://kafka.apache.org/quickstart</a>  （linux版）</p>\\n<p>windows版：<br>\\n首先cmd到kafka的bin下<br>\\n其中启动内置的zk用：zookeeper-server-start.bat D:\\\\environment\\\\kafka_2.12-2.3.0\\\\config\\\\zookeeper.properties<br>\\n启动Kafka用：kafka-server-start.bat D:\\\\environment\\\\kafka_2.12-2.3.0\\\\config\\\\server.properties</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
