name: 部署文档
on:
  push:
    branches:
      - master
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build docs & print file hash
        env:
          NODE_OPTIONS: --max_old_space_size=12288
        run: |
          pnpm run docs:build
          touch src/.vuepress/dist/.nojekyll
          ls src/.vuepress/dist
          find src/.vuepress/dist -type f -print0 | xargs -0 sha256sum > dist-hash.log
          cat dist-hash.log

      # 先上传产物，此时页面会出现Artifacts
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: src/.vuepress/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
