# .github/workflows/docs.yml
name: Deploy VuePress to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/**
      - package.json
      - pnpm-lock.yaml
      - .github/workflows/docs.yml

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 安装pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      # 打包并自动在dist生成 .nojekyll
      - name: Build VuePress
        run: pnpm run docs:build

      # 关键：只上传打包后的dist静态文件，不上传md源码
      - name: Upload static dist
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./src/.vuepress/dist

      - name: Deploy Pages
        id: deploy
        uses: actions/deploy-pages@v4
